# version: '3.8'

# services:
#     db:
#         image: mongo
#         volumes:
#             - ./backend:/data/db
#     dev:
#         container_name: nestjs_api_dev
#         image: nestjs-api-dev:1.0.0
#         build:
#             context: .
#             target: development
#             dockerfile: ./Dockerfile
#         command: npm run start:debug
#         depends_on:
#             - db
#         ports:
#             - 8000:8000
#             - 9229:9229
#         volumes:
#             - .:/usr/src/app
#             - /usr/src/app/node_modules
#         restart: unless-stopped
#         environment:
#             - MONGO_URI=${MONGO_URI}
#             - SECRET_KEY=${SECRET_KEY}

version